fix(windows): use extended paths in Python bootstraps (#4071)
Implicit long-path support is not universal across the Win32 API. The
documented set of APIs covered by the long-path opt-in does not include
DLL loading functions, e.g., LoadLibraryExW:


https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation#functions-without-max_path-restrictions

Always use extended-length paths in Windows bootstrap code and correctly
convert UNC paths to the \\?\UNC\ form.

Experienced this breakage in JAX after the project being switched over
to Bzlmod, which made some paths too long:
https://github.com/jax-ml/jax/actions/runs/31674295160/job/94365413380

```
    File "c:\botcode\w\bazel-out\x64_windows-opt\bin\jax\experimental\jax2tf\tests\multiprocess\jax2tf_multiprocess_test_cpu.exe.runfiles\rules_python++pip+jax_pypi_312_ml_dtypes_cp312_cp312_win_amd64_c1a95399\site-packages\ml_dtypes\_finfo.py", line 17, in <module>
      from ml_dtypes._ml_dtypes_ext import bfloat16
  ImportError: DLL load failed while importing _ml_dtypes_ext: The filename or extension is too long.
```

Already used as a patch in https://github.com/jax-ml/jax/pull/39961

---------

Co-authored-by: Ignas Anikevicius <240938+aignas@users.noreply.github.com>